### ISSUE TITLE
Custom parser

### ISSUE THREAD

**Issue by thoferon** [tibbe/cassava#77] opened 2015-03-08 17:01 UTC
There is no way (that I know of, at least) of passing a custom parser function in place of the one coming from the instance of `FromRecord` or `FromNamedRecord`. Though it's really useful when you need to parameterise the parser, e.g. using column names given by the user.

**Comment by tibbe** [comment] 2015-06-02 22:47
Duplicate of #67.

**Closed by tibbe** 2015-06-02 22:47 UTC
